### PR TITLE
Updated some enemy sprites

### PR DESCRIPTION
**Pull request by PoiuyPL**
Updated some enemy sprites.

### CODE REVIEW

**Comment by Zamiell** [comment]
Shouldn't "222.0.0 - Ring Fly.png" be pink/purple?

**Comment by PoiuyPL** [comment]
It is pink. It is just not that visible because it's small. I will update the attack fly sprite to be darker to be more contrasting.

**Comment by PoiuyPL** [comment]
Done.

**Comment by Zamiell** [comment]
Can you take care of issue #97 as well?

**Comment by PoiuyPL** [comment]
Done

**Comment by Zamiell** [comment]
Thanks.

**Pull request merged**
