### PR TITLE
Booster Pack #4 take 2

### PR DESCRIPTION
**Pull request by PoiuyPL**
Cleaned up pull request #116.

### CODE REVIEW

**Comment by Zamiell** [comment]
can you explain why you converted all the images?

**Comment by PoiuyPL** [comment]
Because the old ones were indexed while newer ones were RGB so it was very mixed. If indexed somehow works better in this case then I can convert all of them to that as well. My idea was just to make it consistent.

**Comment by Zamiell** [comment]
ok, that seems reasonable to me, i was just curious

**Comment by Tempus** [comment]
Merged. Incidentally the pngs were in RGB to avoid pyqt errors and for smaller filesizes. No biggy

**Comment by Zamiell** [comment]
@PoiuyPL can you update the enemies tab with the stone shooter variant?

**Comment by PoiuyPL** [comment]
It is there though? In the Stones category somewhere in the middle.

**Comment by Zamiell** [comment]
the non variant is in there, but not the variant

**Pull request merged**
