### PR TITLE
Configurable quickload functionality

### PR DESCRIPTION
**Pull request by zatherz**
Changelog:
* Move "Open..." option from File menu to "Open file..." under shortcut Ctrl+Shift+O
* New option "Open stage..." under shortcut Ctrl+O in File menu, shows a dialog that allows you to choose a floor from the list
* New option "Set default stage path" in Edit menu, allows you to set the path where "Open stage..." will take stages from

Edit menu
File menu
Open Stage dialog
Stage dialog list
Stage path dialog

### CODE REVIEW

**Comment by Tempus** [comment]
I don't disagree that people normally edit the existing files, as opposed to custom files in some other directory, but there are a few things that need to be cleaned up or fixed before pulling this.

* Set default stage path should store and read the path in QSettings, not in a custom text file. Use `settings.value('SomeIdentifierString')` and settings.getValue('SomeIdentifierString').
* Set default stage path should use QFileDialog.getExistingDirectory(), not QInputDialog
* Set default stage page should set it's default directory for both the path and the selection dialog to the Isaac resources folder, which can be accessed with self.findResourcePath() in the MainWindow.
* The default stage path needs to be validated to ensure the presence of the Isaac stage files. As you have it, the program would error if a non-valid directory is chosen and you attempt to open a stage.
* openMapDefault is not very clean code. The giant if/else from 2355 to 2400 is basically terrible. Make a list of tuples, and populate the input dialog with it, and grab the returned index to do that whole thing in 4 lines instead of 60, and much more maintainably.
* openMapDefault from 2404 to 2420 should also be a one liner, using QSettings as mentioned prior.
* The Set Default File Path option belongs in the File Menu, since it's a file operation, and not the Edit menu. Probably above Take Screenshot, but the exact position is debatable.

**Comment by zatherz** [comment]
I'm fixing all of these except 2., I intended it to be a simple drop down instead of having to choose files. There is the second option for that.

**Comment by Tempus** [comment]
> I'm fixing all of these except 2., I intended it to be a simple drop down instead of having to choose files. There is the second option for that.

The 2nd one, QFileDialog, is not for choosing the stb to open. It's for locating the path to the folder, rather than typing in a path.

**Comment by zatherz** [comment]
Yes, sorry, I didn't read it correctly.

**Comment by zatherz** [comment]
Update changelog:
* Added further crash prevention in findResourcePath() in case the default path does not exist, still needs work
* Stage path selection is now a file selection dialog
* Stages in the Open Stage dialog are now sorted alphabetically
* Code cleaned up, removed big if chain
* Stage path config now uses QSettings
* Set Stage Path option moved to the File menu from Edit
* Default stage path is now the resources/rooms directory
* New "Reset Stage Path" option in the File menu to set the stage

File menu
Open stage
Set stage path

**Comment by zatherz** [comment]
bump

**Comment by Tempus** [comment]
Merged!

**Comment by zatherz** [comment]
Awesome :D

**Pull request merged**
